image: vioneta/{machine}-vionetaos
shadow_repository: ghcr.io/vioneta
build_from:
  aarch64: scratch
  armv7: scratch
  armhf: scratch
  amd64: scratch
  i386: scratch

labels:
  io.hass.type: landingpage
  org.opencontainers.image.source: https://github.com/Vioneta/landingpage
